openapi: 3.0.0
info:
  title: Kadena Wallet Signing API
  description: An API for signing commands
  version: 1.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/STERLINGLONG/KadenaWalletSigningApi/1.0.0
  - url: https://example.com/sign
paths:
  /sign:
    post:
      summary: Sign a command
      operationId: signCommand
      requestBody:
        description: The signing request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigningRequest'
      responses:
        '200':
          description: A signed command
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignedCommand'
  /quicksign:
    post:
      summary: Sign a list of commands
      operationId: quickSignCommands
      requestBody:
        description: The quick sign request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuicksignRequest'
      responses:
        '200':
          description: The result of the quick sign request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuicksignResponse'
components:
  schemas:
    ExecMessage:
      type: object
      description: An exec message. Used to execute pact code directly.
      properties:
        data:
          type: object
        code:
          type: string
      required:
        - data
        - code
    ContinuationMessage:
      type: object
      description: A continuation message. Used to execute a step in a defpact.
      properties:
        pactId:
          type: string
        step:
          type: integer
        rollback:
          type: boolean
        data:
          type: object
        proof:
          type: string
      required:
        - pactId
        - step
        - rollback
        - data
        - proof
    CommandPayload:
      type: object
      description: A continuation or exec command. One or the other must exist or it is invalid.
      properties:
        exec:
          $ref: '#/components/schemas/ExecMessage'
          nullable: true
        cont:
          $ref: '#/components/schemas/ContinuationMessage'
          nullable: true
    Capability:
      type: object
      description: A Pact capability.
      properties:
        name:
          description: The name of the capability, e.g. coin.TRANSFER
          type: string
        args:
          description: The arguments for the capability
          type: array
          items: {}
      required:
        - name
        - args
    SignerCapability:
      type: object
      description: The public key of a signer, and the corresponding capabilities that public key has during the transaction.
      properties:
        pubKey:
          type: string
        clist:
          type: array
          items:
            $ref: '#/components/schemas/Capability'
      required:
        - pubKey
        - clist
    CommandMetadata:
      type: object
      properties:
        chainId:
          description: 'The chain id of the chain the command is being sent to: 0, 1, 15, 19'
          type: string
        gasLimit:
          description: The gas limit for the command
          type: integer
        gasPrice:
          description: The gas price for the command
          type: integer
        sender:
          description: The account of the gas payer
          type: string
        ttl:
          description: The time to live for the command
          type: integer
        creationTime:
          description: The creation time of the command
          type: integer
      required:
        - chainId
        - gasLimit
        - gasPrice
        - sender
        - ttl
        - creationTime
    PactCommandPayload:
      type: object
      description: A payload for a pact command.
      properties:
        payload:
          $ref: '#/components/schemas/CommandPayload'
        signers:
          type: array
          items:
            $ref: '#/components/schemas/SignerCapability'
        meta:
          $ref: '#/components/schemas/CommandMetadata'
        nonce:
          type: string
      required:
        - payload
        - signers
        - meta
        - nonce
      example:
        payload:
          exec:
            data: null
            code: '(coin.transfer "Alice" "Bob" 10.0)'
        signers:
          - pubKey: 368820f80c324bbc7c2b0610688a7da43e39f91d118732671cd9c7500ff43cca
            clist:
              - name: coin.TRANSFER
                args:
                  - Alice
                  - Bob
                  - 10
        meta:
          gasLimit: 1000
          chainId: "0"
          gasPrice: 0.01
          sender: 368820f80c324bbc7c2b0610688a7da43e39f91d118732671cd9c7500ff43cca
        nonce: nonce-value
    Signer:
      type: object
      description: A signer of a pact command. Set the public key null if using with the PactCommandPayload. Set the signature null if used in the CommandSigData.
      properties:
        pubKey:
          type: string
          nullable: true
        sig:
          type: string
          nullable: true
      example:
        pubKey: 'ceb59748b4de3e69c1e100a62035a6aa5e0126bcae263b71ccf012b30f7f6903'
        sig: '756ec1891523f56369c98bf2544a2f91033de9cea53773d7cc4d7812babd9a1d0ab03b706e628bd1636fb5d65083711ba6584bf6ffe471a48657e6a571031306'
    PactCommand:
      type: object
      description: A pact command. Used with the /send and /local endpoints of a Chainweb Node.
      properties:
        cmd:
          description: The JSON stringified PactCommmandPayload
          type: string
        hash:
          description: The blake2b base64 url safe hash of the command
          type: string
        sigs:
          description: The list of Signers with only the sig field set
          type: array
          items:
            $ref: '#/components/schemas/Signer'
      required:
        - cmd
        - hash
        - sigs
      example:
        hash: H6XjdPHzMai2HLa3_yVkXfkFYMgA0bGfsB0kOsHAMuI
        sigs:
          - sig: 8d452109cc0439234c093b5e204a7428bc0a54f22704402492e027aaa9375a34c910d8a468a12746d0d29e9353f4a3fbebe920d63bcc7963853995db015d060f
        cmd: '{"payload":{"exec":{"data":null,"code":"(+ 1 2)"}},
          "signers":[{"pubKey":"368820f80c324bbc7c2b0610688a7da43e39f91d118732671cd9c7500ff43cca"}],
          "meta":{"gasLimit":1000,"chainId":"0","gasPrice":1.0e-2,"sender":"368820f80c324bbc7c2b0610688a7da43e39f91d118732671cd9c7500ff43cca"},
          "nonce":"nonce-value"}'
    DappCap:
      type: object
      description: The Capability sent from a Dapp to the wallet on the /sign endpoint. Role and description are used to display info to the user. Cap is the actual capability.
      properties:
        role:
          type: string
        description:
          type: string
        cap:
          type: object
          properties:
            name:
              type: string
            args:
              type: array
              items:
                type: string
      required:
        - role
        - description
        - cap
    SigningRequest:
      type: object
      description: The object sent to the /sign endpoint of the wallet. The wallet will construct the PactCommandPayload, hash it, sign it, and return the PactCommand.
      properties:
        pactCode:
          type: string
        envData:
          type: object
        sender:
          type: string
        networkId:
          type: string
        chainId:
          type: string
        gasLimit:
          type: number
        gasPrice:
          type: number
        signingPubKey:
          type: string
        ttl:
          type: number
        caps:
          type: array
          items: 
            $ref: '#/components/schemas/DappCap'
      required:
        - pactCode
        - envData
        - sender
        - networkId
        - chainId
        - gasLimit
        - gasPrice
        - signingPubKey
        - ttl
        - caps
    QuicksignRequest:
      type: object
      description: The object sent to the /quicksign endpoint of the wallet. |
        The wallet will loop through each commandSigData, sign it if it can, add the sig to the Signer |
        and return the CommandSigData with the QuicksignOutcome as a QuicksignResult.
      properties:
        commandSigDatas:
          type: array
          items:
            $ref: '#/components/schemas/CommandSigData'
      required:
        - commandSigDatas
    CommandSigData:
      type: object
      description: Has a JSON stringifie PactCommandPayload and the requested signatures.
      properties:
        cmd:
          type: string
        sigs:
          type: array
          description: The list of Signers with the public field set. Missing sig means that signature hasn't been acquired yet.
          items:
            $ref: '#/components/schemas/Signer'
      required:
        - cmd
        - sigs
      example:
        commandSigDatas:
        - sigs:
            - pubKey: "ae18efd16cbd49e9a92552a2589ac01491b486fbcbb1e3f07980f945597e2033"
            - pubKey: "fa781bdd858cd2380b5e2b654e58035f7189a6e8158686a1bb7eabb585a56e7f"
              sig: null
            - pubKey: "d61c2b4d8151cd0a7599790a6a905a96dc1028b5e61181e08104e60f28ad8997"
              sig: "a41b1c481414b0a0bac27c1f95f03d058cf1dc7ace571cf7b7a74be34e90116096dac8744adc0b94ffc16241cc87f513ea7f999802b3b6e58a1139c56881f800"
          cmd: "{\"networkId\":\"testnet04\",\"payload\":{\"exec\":{\"data\":null,\"code\":\"(enforce-keyset (read-keyset 'ks))\"}},\"signers\":[{\"pubKey\":\"ae18efd16cbd49e9a92552a2589ac01491b486fbcbb1e3f07980f945597e2033\"},{\"pubKey\":\"fa781bdd858cd2380b5e2b654e58035f7189a6e8158686a1bb7eabb585a56e7f\"},{\"pubKey\":\"d61c2b4d8151cd0a7599790a6a905a96dc1028b5e61181e08104e60f28ad8997\"}],\"meta\":{\"creationTime\":1664393516,\"ttl\":1800,\"gasLimit\":100,\"chainId\":\"0\",\"gasPrice\":1.0e-6,\"sender\":\"k:ae18efd16cbd49e9a92552a2589ac01491b486fbcbb1e3f07980f945597e2033\"},\"nonce\":\"2022-09-28 19:31:56.965212 UTC\"}"
    QuicksignOutcome:
      type: object
      description: The outcome of the quicksign operation on a single CommandSigData.
      properties:
        result:
          type: string
        hash:
          type: string
          nullable: true
        msg:
          type: string
          nullable: true
      required:
        - result
        - hash
        - msg
    QuicksignResult:
      type: object
      description: The result of the quicksign operation on a single CommandSigData. Contains a CommandSigData and a QuicksignOutcome.
      properties:
        commandSigData:
          $ref: '#/components/schemas/CommandSigData'
        outcome:
          $ref: '#/components/schemas/QuicksignOutcome'
      required:
        - commandSigData
        - outcome
    QuicksignError:
      type: object
      description: The error that occurred during the quicksign operation.
      properties:
        type:
          type: string
          enum: ['reject', 'emptyList', 'other']
        msg:
          type: string
          nullable: true
      required:
        - type
    QuicksignResponse:
      type: object
      description: The response from the /quicksign endpoint of the wallet. Contains either a list of QuicksignResults or a QuicksignError. |
        One of the two must exist or it is an invalid response.
      properties:
        responses:
          type: array
          items:
            $ref: '#/components/schemas/QuicksignResult'
          nullable: true
        error:
          $ref: '#/components/schemas/QuicksignError'
          nullable: true

